# Generated by Django 2.1.4 on 2019-01-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='departments.Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
